name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "assets/*"
    branches: [main, dev]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Install Dependencies
      #   run: |
      #     if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
      #       sudo apt-get update
      #       sudo apt-get install libfreetype6-dev libx11-dev libxcursor-dev libxrandr-dev libudev-dev libgl1-mesa-dev libflac-dev libogg-dev libvorbis-dev libvorbisenc2 libvorbisfile3 libopenal-dev libpthread-stubs0-dev
      #     elif [ "${{ matrix.os }}" == "macos-latest" ]; then
      #       brew install sfml
      #     fi

      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          cmake --build . --config Release

      - name: Test
        run: |
          cd build
          ctest -C Release --verbose
